name: panvimdoc

on:
  push:
    branches:
      - '*'

permissions:
  contents: write

jobs:
  docs:
    runs-on: ubuntu-latest
    name: pandoc to vimdoc
    steps:
      - uses: actions/checkout@v2
      - uses: kdheepak/panvimdoc@main
        with:
          vimdoc: 'vim-dirvish-git-lua'
          pandoc: 'README.md'
          description: '*vim-dirvish-git-lua*'

      - name: Commit and push documentation
        uses: ./.github/actions/commit-and-push
        with:
          commit-message: 'Update Vimdoc based on README'
          files: 'doc/*'
          github_token: ${{ secrets.GITHUB_TOKEN }}

